import Foundation

struct PrivacyFilter: Equatable {
    let excludedBundleIDs: Set<String>
    let concealedTypes: Set<String>

    func shouldCapture(bundleID: String?, types: [String]) -> Bool {
        if let id = bundleID, excludedBundleIDs.contains(id) {
            return false
        }
        let lowered = types.map { $0.lowercased() }
        for type in lowered where concealedTypes.contains(type) {
            return false
        }
        return true
    }

    static let defaultExcludedBundleIDs: Set<String> = [
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword4",
        "com.1password.1password",
        "com.1password.1password-launcher",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane"
    ]

    static let concealedTypes: Set<String> = [
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.autogeneratedtype",
        "com.agilebits.onepassword",
        "pasteboard generator type"
    ]

    static let permissive = PrivacyFilter(excludedBundleIDs: [], concealedTypes: [])
}
